on: push
name: Check Assignment
jobs:
  check-allowed-files:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dukestatsci/r_gh_actions:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Check Files
      run: |
        checklist::quit_on_failure({
          checklist::check_allowed_files(c("midterm1.qmd", "midterm1.Rproj", "README.md", "data/*"))
        })
      shell: Rscript {0}
  check-renders:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dukestatsci/r_gh_actions:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Check Renders
      run: |
        checklist::check_qmd_renders("midterm1.qmd", install_missing = TRUE)
      shell: Rscript {0}
